#name : exception ... { ... }
# --
try {
	throw new Exception($0);
} catch (Exception $e) {
	$e->getMessage();
}